name: Build crx
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.should_build.outputs.should_run }}
    steps:
      - name: Should build?
        id: should_build
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          elif echo "${{ github.event.head_commit.message }}" | grep -iq "^bump version"; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check
    if: needs.check.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install crx

      - name: Build crx 
        env:
          REPO_OWNER: ${{ github.repository_owner }} 
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "${{ secrets.CRX_PRIVATE_KEY }}" > extension.pem
          ./build.sh

      - name: Publish extension.crx and update.xml
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

