name: Build crx
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install crx

      - name: Build crx 
        env:
          REPO_OWNER: ${{ github.repository_owner }} 
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "${{ secrets.CRX_PRIVATE_KEY }}" > extension.pem
          ./build.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

